### ISSUE TITLE
Spannmittel

### ISSUE THREAD

**Issue by vschlegel** [reaktor23/Fraese-Config#8]
1. Multiplexplatte mit Gewinderaster versehen, mit Senkkopfschrauben (oben flach) auf die Maschine schrauben.
2. Zeno damit nerven, dass er Spannbrieden in verschiedenen Variationen drucken soll.
3. Bouncy nerven, dass er Rändelschrauben besorgt (wie die an der Fräsen-Bildschirmhalterung)
4. Fräs Fräs :)

**Comment by vschlegel** [comment]
https://twitter.com/fleaz_/status/1177306618133917696

**Comment by Bouni** [comment]
Es wurde 2x dieses Spannittelset bestellt: https://www.sorotec.de/shop/24-Teiliges-Stufenspannspratzen-Set-M8---10er-Nut.html
Damit sollte das Thema Spannmittel eigentlich erschlagen sein.
